### PR TITLE
Add reference to Terms of X-Road document

### PR DESCRIPTION
**Pull request by hanhaka**

### CODE REVIEW

**Comment by VitaliStupin** [comment]
What about existing documents? Do we need to remove terms and abbreviations? For example it is a lot easier to read a protocol document which defines a couple of terms needed for better understanding of that document, then to just have a reference to a terms document that has a lot of unnecessary stuff.

**Comment by hanhaka** [comment]
Originally I was thinking that terms and abbreviations section would be removed from all the existing documents. But after reading your comment and re-thinking the matter, it would be better if the terms that are specific for the document in question would be defined in that document itself (it makes reading a lot easier) and only general X-Road related terms and abbreviations would be moved to Terms of X-Road document. 

I will rephrase the text in FormattingStyleGuide.md and make a new commit.

**Review by JyrgenSuvalov — COMMENTED** [review]
Overall I approve, but we're having some trouble understanding when and where document specific definitions would be appropriate. The current wording is a little ambiguous in that regard. Could you perhaps give us some examples of document specific terms that should be defined in the document itself?

**Comment by hanhaka** [comment]
This is though one :) ...made a new commit to clarify more how to define terms and abbreviations in documents.

**Review by VitaliStupin — APPROVED** [review]

**Pull request merged**
